#!/usr/bin/env python3
"""One-shot plan bootstrap from a user's product idea (auto scale + ultraplan route)."""

from __future__ import annotations

import argparse
from datetime import date
from pathlib import Path

from plan_extract import extract_modules
from plan_paths import SCALE_PLATFORM, product_map_file, scale_file, ultraplan_status_file
from plan_scale import infer_scale, render_scale_report
from ultraplan_harness import decompose_from_list, decompose_from_map, find_next_incomplete, update_ultraplan_status
from workspace_utils import resolve_workspace


def write_idea(workspace: Path, text: str) -> Path:
    path = workspace / "plan" / "IDEA.md"
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(
        "\n".join(
            [
                "# Product Idea",
                "",
                f"**Captured:** {date.today().isoformat()}",
                "",
                text.strip(),
                "",
            ]
        ),
        encoding="utf-8",
    )
    return path


def render_bootstrap(
    workspace: Path,
    *,
    idea: str,
    scale: str,
    scale_result: dict,
    modules: list[tuple[str, str]],
    decomposed: list[dict] | None,
    next_step: dict | None,
) -> str:
    lines = [
        "# Plan Bootstrap",
        "",
        f"**Generated:** {date.today().isoformat()}",
        "",
        "Auto-generated by `loop plan-loop \"<idea>\"`. **Agent: read this after session-start.**",
        "",
        "## Idea",
        "",
        idea.strip()[:2000],
        "",
        f"## Scale: `{scale}`",
        "",
    ]
    for reason in scale_result.get("reasons", []):
        lines.append(f"- {reason}")
    lines.extend(["", "## What ran automatically", ""])
    lines.append("- Wrote `plan/PLAN_SCALE.md`")
    lines.append("- Wrote `plan/IDEA.md`")
    if scale == SCALE_PLATFORM:
        if modules:
            lines.append(f"- Extracted {len(modules)} module(s) from idea text")
            lines.append("- Wrote `plan/PRODUCT_MAP.md` + step stubs + ultraplan folders")
        else:
            lines.append("- Platform scale but modules not extracted — agent must propose `PRODUCT_MAP.md` rows")
        lines.append("- Refreshed `plan/ULTRAPLAN_STATUS.md`")
    else:
        lines.append("- Convenient scale — use standard step plan + feature spec (no ultraplan folders yet)")

    if decomposed:
        lines.extend(["", "## Modules created", ""])
        for item in decomposed:
            lines.append(f"- **{item['id']}** {item['title']} → `{item.get('folder', item.get('step', ''))}`")

    lines.extend(["", "## Agent next action", ""])
    if scale == SCALE_PLATFORM:
        if next_step:
            lines.append(
                f"1. Run **`skills/ultraplan/SKILL.md`** on step **{next_step['id']} — {next_step['title']}** "
                f"(fill all files under `plan/steps/`)."
            )
            lines.append("2. One step per session — do not shallow-plan every module at once.")
            lines.append("3. When that step's pack is complete → feature spec + task-compiler for that step only.")
        elif not modules:
            lines.append("1. Propose module list in `plan/PRODUCT_MAP.md` (confirm with user if unclear).")
            lines.append("2. Re-run `loop plan-loop \"<idea>\"` or `loop plan-loop decompose` after map is filled.")
        else:
            lines.append("1. All ultraplan packs marked structurally ready — validate content depth.")
            lines.append("2. Continue `/plan-loop` grill, evidence, council, then feature spec on active step.")
    else:
        lines.append("1. Continue standard `/plan-loop`: init product, one `plan/step_01_*.md`, feature spec.")
        lines.append("2. If the idea grows into many modules, re-run `loop plan-loop \"<idea>\"` to re-detect scale.")

    lines.extend(
        [
            "",
            "## User command (only this is required)",
            "",
            "```bash",
            "loop plan-loop \"<product idea in plain language>\"",
            "```",
            "",
            "Or `/plan-loop <idea>` / `/loop-engine <idea>` — agent runs the same bootstrap.",
            "",
        ]
    )
    return "\n".join(lines)


def bootstrap_plan(workspace: Path, idea: str) -> dict:
    idea = idea.strip()
    if not idea:
        raise SystemExit("idea text required")

    write_idea(workspace, idea)
    scale_result = infer_scale(workspace, extra=idea)
    scale = scale_result["scale"]

    scale_path = scale_file(workspace)
    scale_path.parent.mkdir(parents=True, exist_ok=True)
    scale_path.write_text(render_scale_report(workspace, scale_result), encoding="utf-8")

    modules = extract_modules(idea) if scale == SCALE_PLATFORM else []
    decomposed: list[dict] | None = None

    if scale == SCALE_PLATFORM and len(modules) >= 2:
        titles = [m[0] for m in modules]
        types = [m[1] for m in modules]
        decomposed = decompose_from_list(workspace, titles, types)
    elif scale == SCALE_PLATFORM and product_map_file(workspace).exists():
        try:
            decomposed = decompose_from_map(workspace)
        except SystemExit:
            decomposed = None

    update_ultraplan_status(workspace)
    next_step = find_next_incomplete(workspace) if scale == SCALE_PLATFORM else None

    bootstrap_path = workspace / "plan" / "PLAN_BOOTSTRAP.md"
    bootstrap_path.write_text(
        render_bootstrap(
            workspace,
            idea=idea,
            scale=scale,
            scale_result=scale_result,
            modules=modules,
            decomposed=decomposed,
            next_step=next_step,
        ),
        encoding="utf-8",
    )

    return {
        "scale": scale,
        "modules": len(modules),
        "decomposed": len(decomposed or []),
        "next": next_step,
        "bootstrap": str(bootstrap_path),
    }


def main() -> int:
    parser = argparse.ArgumentParser(description="Auto-bootstrap plan from a product idea string.")
    parser.add_argument("--text", required=True, help="Full product idea in plain language.")
    parser.add_argument("--workspace", default=None)
    args = parser.parse_args()

    workspace = resolve_workspace(args.workspace)
    result = bootstrap_plan(workspace, args.text)

    print(f"scale={result['scale']}")
    print(f"modules_extracted={result['modules']}")
    print(f"modules_decomposed={result['decomposed']}")
    if result["next"]:
        nxt = result["next"]
        print(f"ultraplan_next=step {nxt['id']} — {nxt['title']}")
    print(f"bootstrap={result['bootstrap']}")
    print("Read plan/PLAN_BOOTSTRAP.md first.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
