#!/usr/bin/env python3
"""Always-on session lifecycle: start recall + end memory review (tool-agnostic)."""

from __future__ import annotations

import argparse
import json
from datetime import datetime, timezone
from pathlib import Path

from agent_skill_router import run_router as run_agent_router
from frontend_skill_router import run_router
from feature_paths import read_active_feature
from memory_curator import apply_report, propose_updates, render_report
from memory_paths import ensure_memory_layout, session_bootstrap_paths, state_db
from pending_writes import list_pending
from session_recall import append_handoff_pointer, build_query, extract_keywords, render_recall
from session_store import init_db, log_session, recent_sessions, search_sessions
from workspace_utils import resolve_workspace


SESSION_META = ".loop/session.json"
MANIFEST = "plan/SESSION_MANIFEST.md"
CLOSEOUT = "plan/SESSION_CLOSEOUT.md"


def _now() -> str:
    return datetime.now(timezone.utc).isoformat()


def _meta_path(workspace: Path) -> Path:
    return workspace / SESSION_META


def read_meta(workspace: Path) -> dict:
    path = _meta_path(workspace)
    if not path.exists():
        return {}
    try:
        return json.loads(path.read_text(encoding="utf-8"))
    except json.JSONDecodeError:
        return {}


def write_meta(workspace: Path, data: dict) -> None:
    path = _meta_path(workspace)
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(json.dumps(data, indent=2) + "\n", encoding="utf-8")


def run_recall(workspace: Path, query: str | None = None, limit: int = 5) -> int:
    db = state_db(workspace)
    init_db(db)
    keywords = extract_keywords(workspace)
    q = query or build_query(keywords)
    hits = search_sessions(db, q, limit=limit)
    if not hits:
        hits = recent_sessions(db, limit=limit)
    out = workspace / "plan" / "SESSION_RECALL.md"
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text(render_recall(workspace, hits), encoding="utf-8")
    append_handoff_pointer(workspace)
    log_session(
        db,
        workspace=str(workspace),
        command="session-start",
        title="Session recall (lifecycle)",
        body=f"query={q!r}; hits={len(hits)}",
        tags="recall lifecycle",
    )
    return len(hits)


def _hierarchy(workspace: Path, *, stage: bool = True) -> dict:
    """Refresh product-hierarchy links and reports. Never raises - like _auto_update."""
    try:
        from hierarchy_sync import run

        return run(workspace, stage=stage)
    except Exception as exc:  # noqa: BLE001 - a hierarchy problem must not block a session
        return {"enabled": False, "role": None, "error": f"{exc.__class__.__name__}: {exc}"}


def _parent_findings(workspace: Path) -> dict:
    """What this sub-product still owes its parent an answer about. Never raises.

    Computed once here and its count persisted, so `plan_phase` stays a cheap
    state signal rather than re-running the drift checks to route a phase.
    """
    try:
        import parent_inbox

        return parent_inbox.inbox(workspace)
    except Exception:
        return {"parent": None, "ask": [], "report": [], "total": 0}


def render_manifest(
    workspace: Path,
    *,
    command: str | None,
    tool: str | None,
    hits: int,
    auto_skills: list[str],
    auto_agent_skills: list[str] | None = None,
    update_status: dict | None = None,
    hierarchy: dict | None = None,
    findings: dict | None = None,
) -> str:
    auto_agent_skills = auto_agent_skills or []
    lines = [
        "# Session Manifest",
        "",
        f"**Generated:** {_now()}",
        f"**Workspace:** `{workspace}`",
        "",
        "Always-on memory bootstrap. **Every agent must read these files in order** before acting.",
        "Regenerated by `loop session-start` (any coding agent: Cursor, Claude Code, Codex, OpenCode, Grok, ...).",
        "",
        "## Lifecycle",
        "",
        "- **Start:** `loop session-start` (or `/session-start`) - you are here",
        "- **End:** `loop session-end` (or `/session-end`) before stopping",
        "",
    ]
    if command:
        lines.append(f"- **Active command:** `{command}`")
    if tool:
        lines.append(f"- **Tool hint:** `{tool}`")
    lines.append(f"- **Session recall hits:** {hits}")
    if update_status:
        if update_status.get("updated"):
            lines.append(f"- **App auto-updated:** {update_status['updated']} commit(s) pulled; routers refreshed")
        elif update_status.get("notice"):
            lines.append(f"- **App update:** {update_status['notice']}")
    lines.append("")

    lines.extend(["## Read order", ""])
    lines.append(f"1. `{MANIFEST}` (this file)")
    idx = 2
    for path in session_bootstrap_paths(workspace, command):
        if path.name == "SESSION_MANIFEST.md":
            continue
        try:
            rel = path.relative_to(workspace).as_posix()
        except ValueError:
            rel = str(path)
        exists = "ok" if path.exists() else "missing"
        lines.append(f"{idx}. `{rel}` ({exists})")
        idx += 1

    if auto_skills:
        lines.extend(["", "## Auto frontend skills", ""])
        for name in auto_skills:
            lines.append(f"- `{name}` - see `plan/AUTO_SKILLS.md`")

    if auto_agent_skills:
        lines.extend(["", "## Auto agent-development skills", ""])
        for name in auto_agent_skills:
            lines.append(f"- `{name}` - see `plan/AUTO_AGENT_SKILLS.md`")

    if hierarchy:
        try:
            from hierarchy_sync import manifest_block

            lines.extend(manifest_block(workspace, hierarchy))
        except Exception:
            pass

    # Placed right after the hierarchy block: every command reads the manifest first,
    # so this is the one channel that reaches /plan-loop, /product-develop,
    # /loop-engine and /revise-plan without wiring each of them separately.
    if findings:
        try:
            from parent_inbox import manifest_block as findings_block

            lines.extend(findings_block(workspace, findings))
        except Exception:
            pass

    bootstrap = workspace / "plan" / "PLAN_BOOTSTRAP.md"
    if bootstrap.exists():
        lines.extend(
            [
                "",
                "## Plan bootstrap",
                "",
                f"- Read `{bootstrap.relative_to(workspace).as_posix()}` - auto scale + ultraplan route from user idea.",
            ]
        )

    if command in ("/plan-loop", "/ultraplan-loop", "/loop-engine", "/spec-clarify", "/spec-checklist") or (
        workspace / "plan" / "main_plan.md"
    ).exists():
        try:
            from plan_phase import render_phase_block

            lines.extend(["", render_phase_block(workspace, heading="## Plan phase")])
        except Exception:
            pass

    # The development counterpart: one phase file and its skills, instead of the
    # 32-item Read First list a build session used to work through.
    from memory_paths import _is_build_command

    if _is_build_command(command) and (workspace / "TASKS.yml").exists():
        try:
            from build_phase import render_phase_block as render_build_phase

            lines.extend(["", render_build_phase(workspace, heading="## Build phase")])
        except Exception:
            pass

    active = read_active_feature(workspace)
    if active:
        lines.extend(
            [
                "",
                "## Active feature",
                "",
                f"- **ID:** `{active.get('id')}` - {active.get('title', '')}",
                f"- **Path:** `{active.get('path')}`",
                "- Read `spec.md`, `feature-plan.md`, `tasks.md` in that folder during `/product-develop`.",
            ]
        )

    lines.extend(
        [
            "",
            "## Rules",
            "",
            "- Reuse `plan/SESSION_RECALL.md` - do not re-ask settled decisions.",
            "- Update `HANDOFF.md`, `DOUBTS.md`, `memories/MEMORY.md` before `loop session-end`.",
            "- Memory curator writes this workspace's memory directly; only cross-workspace and skill writes wait for `loop pending approve`.",
            "",
        ]
    )
    return "\n".join(lines)


def _auto_maintenance(workspace: Path) -> list[str]:
    """Chores that used to be separate commands the user had to remember.

    Only work that is deterministic, idempotent, and creates no new plan content
    belongs here - it runs on every `loop session-start`, so anything that authors
    content would author it again every session. That rules out
    `loop plan-loop decompose` (it creates a step pack per map row, including rows
    the plan has deliberately deferred) and `loop sync` (it appends dated notes to
    MEMORY.md and HANDOFF.md). Both stay explicit.
    """
    actions: list[str] = []

    try:  # was: loop plan-loop ultraplan status
        from plan_paths import product_map_file
        from ultraplan_harness import update_ultraplan_status

        if product_map_file(workspace).exists():
            update_ultraplan_status(workspace)
            actions.append("ultraplan status refreshed")
    except Exception:
        pass

    try:  # the task-scoped slice a build session reads instead of the whole files
        from task_context import write_context

        if write_context(workspace) is not None:
            actions.append("build context refreshed for the active task")
    except Exception:
        pass

    try:  # was: loop pending dedupe
        from pending_writes import dedupe_pending

        dropped = dedupe_pending(workspace)
        if dropped:
            actions.append(f"dropped {len(dropped)} duplicate pending write(s)")
    except Exception:
        pass

    try:  # generated files that no longer match what they were generated from
        from freshness import stale_views

        stale = stale_views(workspace)
        if stale:
            names = ", ".join(item["view"] for item in stale[:3])
            actions.append(
                f"{len(stale)} generated file(s) out of date ({names}"
                f"{', ...' if len(stale) > 3 else ''}) - `loop fresh`"
            )
    except Exception:
        pass

    try:  # the reference index, and one more day of edge history
        import graph_index

        graph = graph_index.build(workspace)
        if graph["nodes"]:
            graph_index.write(workspace, graph)
            graph_index.record_history(workspace, graph)
            broken = len(graph.get("dangling", []))
            if broken:
                actions.append(f"{broken} dangling reference(s) - run `loop graph dangling`")
    except Exception:
        pass

    try:  # one-time cleanup of the retired drift-note queue
        from parent_inbox import drop_legacy_queue

        stale = drop_legacy_queue(workspace)
        if stale:
            actions.append(f"cleared {stale} staged drift note(s) - findings are derived now")
    except Exception:
        pass

    return actions


def _auto_update() -> dict:
    """Silent, throttled app self-update. Never raises."""
    try:
        from auto_update import maybe_auto_update, resolve_app_root
        from loop_home import global_data_home

        return maybe_auto_update(resolve_app_root(), global_data_home())
    except Exception as exc:
        return {"skip": f"error: {exc.__class__.__name__}"}


def session_start(
    workspace: Path,
    *,
    command: str | None = None,
    tool: str | None = None,
    text: str = "",
    skip_recall: bool = False,
) -> dict:
    ensure_memory_layout(workspace)
    update_status = _auto_update()
    hits = 0
    if not skip_recall:
        hits = run_recall(workspace)

    picks = run_router(workspace, extra=text, write=True)
    auto_names = [name for name, _ in picks]

    agent_picks = run_agent_router(workspace, extra=text, write=True)
    auto_agent_names = [name for name, _ in agent_picks]

    hierarchy = _hierarchy(workspace)
    findings = _parent_findings(workspace)
    maintenance = _auto_maintenance(workspace)

    plan_bootstrap = None
    if text.strip() and command and any(c in (command or "") for c in ("/plan-loop", "/loop-engine", "plan", "loop-engine")):
        try:
            from plan_idea import bootstrap_plan

            plan_bootstrap = bootstrap_plan(workspace, text.strip())
        except Exception as exc:
            plan_bootstrap = {"error": str(exc)}

    manifest_path = workspace / MANIFEST
    manifest_path.parent.mkdir(parents=True, exist_ok=True)
    manifest_path.write_text(
        render_manifest(
            workspace,
            command=command,
            tool=tool,
            hits=hits,
            auto_skills=auto_names,
            auto_agent_skills=auto_agent_names,
            update_status=update_status,
            hierarchy=hierarchy,
            findings=findings,
        ),
        encoding="utf-8",
    )

    meta = read_meta(workspace)
    meta.update(
        {
            "started_at": _now(),
            "ended_at": None,
            "command": command,
            "tool": tool,
            "recall_hits": hits,
            "auto_skills": auto_names,
            "auto_agent_skills": auto_agent_names,
            "manifest": MANIFEST,
            "role": hierarchy.get("role"),
            "sub_products": hierarchy.get("children", 0),
            "maintenance": maintenance,
            # Read by plan_phase to route the parent-findings phase without
            # re-running the drift checks.
            "open_parent_findings": findings.get("total", 0),
            "parent_findings_ask": len(findings.get("ask") or []),
        }
    )
    write_meta(workspace, meta)

    db = state_db(workspace)
    init_db(db)
    log_session(
        db,
        workspace=str(workspace),
        command=command or "session-start",
        title="Session started",
        body=(
            f"manifest={MANIFEST}; recall_hits={hits}; auto_skills={auto_names}; "
            f"auto_agent_skills={auto_agent_names}; role={hierarchy.get('role')}; "
            f"sub_products={hierarchy.get('children', 0)}; drift={hierarchy.get('counts')}"
        ),
        tags="lifecycle start hierarchy",
    )

    return {
        "hits": hits,
        "auto_skills": auto_names,
        "auto_agent_skills": auto_agent_names,
        "manifest": str(manifest_path),
        "hierarchy": hierarchy,
        "maintenance": maintenance,
        "findings": findings,
    }


def render_closeout(workspace: Path, report: dict, actions: list[str], pending: int) -> str:
    lines = [
        "# Session Closeout",
        "",
        f"**Generated:** {_now()}",
        f"**Workspace:** `{workspace}`",
        "",
        "Always-on memory closeout from `loop session-end`. Read `plan/MEMORY_REVIEW.md` for details.",
        "",
        "## Memory usage",
        "",
        f"- Memory: {report['memory_usage']['chars']}/{report['memory_usage']['limit']} chars",
        f"- User: {report['user_usage']['chars']}/{report['user_usage']['limit']} chars",
        "",
        "## Actions",
        "",
    ]
    if actions:
        lines.extend(f"- {a}" for a in actions)
    else:
        lines.append("- Memory within limits; nothing to curate.")
    lines.extend(
        [
            "",
            f"## Pending writes: {pending}",
            "",
        ]
    )
    if pending:
        lines.append(
            "These need a human decision (cross-workspace or skill writes). "
            "Run `loop pending list`, then approve or reject by id."
        )
    else:
        lines.append("Nothing waiting on a human.")
    lines.extend(["", "## Next agent", "", "Read `plan/SESSION_MANIFEST.md` after the next `loop session-start`.", ""])
    return "\n".join(lines)


def session_end(
    workspace: Path,
    *,
    command: str | None = None,
    summary: str = "",
    apply: bool = True,
    stage: bool = False,
) -> dict:
    ensure_memory_layout(workspace)
    report = propose_updates(workspace)
    review_path = workspace / "plan" / "MEMORY_REVIEW.md"
    review_path.parent.mkdir(parents=True, exist_ok=True)
    review_path.write_text(render_report(workspace, report), encoding="utf-8")

    # This workspace's own memory applies directly - see apply_report(). Only
    # cross-workspace and skill writes go through the approval queue, so a
    # closeout no longer leaves work for the user to remember to do.
    actions = apply_report(workspace, report, stage_only=stage)

    converge_note = ""
    if command and "product-develop" in (command or ""):
        try:
            from feature_converge import converge

            report_path, _ = converge(workspace)
            if report_path:
                converge_note = str(report_path.relative_to(workspace))
        except Exception as exc:
            converge_note = f"feature converge skipped: {exc}"
    if converge_note:
        actions.append(f"feature converge: {converge_note}")

    # Compact finished work at the *end* of a session, never at the start - the
    # session that just closed a task should still see it in full when it writes
    # its handoff. Budget-gated, so a small workspace is never touched.
    try:
        from state_archive import run as compact_state

        for item in compact_state(workspace):
            if item.get("compacted"):
                saved = item["before"] - item["after"]
                actions.append(
                    f"{item['file']}: compacted {len(item['compacted'])} finished entry(ies), "
                    f"-{saved:,} chars (detail in plan/archive/)"
                )
    except Exception:
        pass

    # Refresh the roll-up so the next agent inherits a current view of the tree.
    hierarchy = _hierarchy(workspace, stage=False)
    if hierarchy.get("children"):
        counts = hierarchy.get("counts", {})
        actions.append(
            f"hierarchy: {hierarchy['children']} sub-product(s), "
            f"{counts.get('error', 0)} error / {counts.get('warn', 0)} warning finding(s) "
            "in plan/SUBPRODUCTS.md"
        )
    elif hierarchy.get("parent"):
        actions.append(f"hierarchy: sub-product of `{hierarchy['parent']}` (plan/PARENT_CONTEXT.md refreshed)")

    pending = len(list_pending(workspace))

    closeout_path = workspace / CLOSEOUT
    closeout_path.write_text(render_closeout(workspace, report, actions, pending), encoding="utf-8")

    handoff_excerpt = ""
    handoff = workspace / "HANDOFF.md"
    if handoff.exists():
        handoff_excerpt = handoff.read_text(encoding="utf-8", errors="ignore")[:800]

    body = summary.strip() or handoff_excerpt or review_path.read_text(encoding="utf-8")[:1200]
    db = state_db(workspace)
    init_db(db)
    log_session(
        db,
        workspace=str(workspace),
        command=command or "session-end",
        title="Session ended",
        body=body[:2000],
        tags="lifecycle end memory-review",
    )

    meta = read_meta(workspace)
    meta["ended_at"] = _now()
    meta["last_closeout"] = CLOSEOUT
    meta["pending_writes"] = pending
    write_meta(workspace, meta)

    return {
        "review": str(review_path),
        "closeout": str(closeout_path),
        "pending": pending,
        "actions": actions,
        "hierarchy": hierarchy,
    }


def main() -> int:
    parser = argparse.ArgumentParser(description="Always-on session lifecycle (start/end).")
    parser.add_argument("phase", choices=("start", "end"))
    parser.add_argument("--workspace", default=None)
    parser.add_argument("--command", default=None, help="Active loop command e.g. /product-develop")
    parser.add_argument("--tool", default=None, help="Tool hint e.g. cursor, claude, codex")
    parser.add_argument("--text", default="", help="Extra context for routers (user message).")
    parser.add_argument("--skip-recall", action="store_true")
    parser.add_argument("--apply", action="store_true", help="Apply memory directly on end (default).")
    parser.add_argument("--stage", action="store_true", help="Stage this workspace's memory writes for approval instead of applying.")
    parser.add_argument("--summary", default="", help="Optional closeout summary for state.db")
    args = parser.parse_args()

    workspace = resolve_workspace(args.workspace)

    if args.phase == "start":
        result = session_start(
            workspace,
            command=args.command,
            tool=args.tool,
            text=args.text,
            skip_recall=args.skip_recall,
        )
        print(f"session-start ok")
        print(f"  manifest: {result['manifest']}")
        print(f"  recall hits: {result['hits']}")
        if result["auto_skills"]:
            print(f"  auto skills: {', '.join(result['auto_skills'])}")
        if result["auto_agent_skills"]:
            print(f"  auto agent skills: {', '.join(result['auto_agent_skills'])}")
        for action in result.get("maintenance", []):
            print(f"  auto: {action}")
        hier = result.get("hierarchy") or {}
        if hier.get("children"):
            counts = hier.get("counts", {})
            print(
                f"  hierarchy: main with {hier['children']} sub-product(s); "
                f"{counts.get('error', 0)} error finding(s) - read plan/SUBPRODUCTS.md"
            )
        elif hier.get("parent"):
            print(f"  hierarchy: sub-product of `{hier['parent']}` - read plan/PARENT_CONTEXT.md")
        found = result.get("findings") or {}
        if found.get("total"):
            print(
                f"  parent findings: {found['total']} open "
                f"({len(found.get('ask') or [])} need a decision) - run `loop findings ask`"
            )
        print("  read plan/SESSION_MANIFEST.md first")
        return 0

    result = session_end(workspace, command=args.command, summary=args.summary, stage=args.stage)
    print("session-end ok")
    print(f"  review: {result['review']}")
    print(f"  closeout: {result['closeout']}")
    print(f"  pending writes: {result['pending']}")
    for action in result["actions"]:
        print(f"  - {action}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
