#!/usr/bin/env python3
"""Always-on session lifecycle: start recall + end memory review (tool-agnostic)."""

from __future__ import annotations

import argparse
import json
from datetime import datetime, timezone
from pathlib import Path

from agent_skill_router import run_router as run_agent_router
from frontend_skill_router import run_router
from feature_paths import read_active_feature
from memory_curator import apply_report, propose_updates, render_report
from memory_paths import ensure_memory_layout, session_bootstrap_paths, state_db
from pending_writes import list_pending
from session_recall import append_handoff_pointer, build_query, extract_keywords, render_recall
from session_store import init_db, log_session, recent_sessions, search_sessions
from workspace_utils import resolve_workspace


SESSION_META = ".loop/session.json"
MANIFEST = "plan/SESSION_MANIFEST.md"
CLOSEOUT = "plan/SESSION_CLOSEOUT.md"


def _now() -> str:
    return datetime.now(timezone.utc).isoformat()


def _meta_path(workspace: Path) -> Path:
    return workspace / SESSION_META


def read_meta(workspace: Path) -> dict:
    path = _meta_path(workspace)
    if not path.exists():
        return {}
    try:
        return json.loads(path.read_text(encoding="utf-8"))
    except json.JSONDecodeError:
        return {}


def write_meta(workspace: Path, data: dict) -> None:
    path = _meta_path(workspace)
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(json.dumps(data, indent=2) + "\n", encoding="utf-8")


def run_recall(workspace: Path, query: str | None = None, limit: int = 5) -> int:
    db = state_db(workspace)
    init_db(db)
    keywords = extract_keywords(workspace)
    q = query or build_query(keywords)
    hits = search_sessions(db, q, limit=limit)
    if not hits:
        hits = recent_sessions(db, limit=limit)
    out = workspace / "plan" / "SESSION_RECALL.md"
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text(render_recall(workspace, hits), encoding="utf-8")
    append_handoff_pointer(workspace)
    log_session(
        db,
        workspace=str(workspace),
        command="session-start",
        title="Session recall (lifecycle)",
        body=f"query={q!r}; hits={len(hits)}",
        tags="recall lifecycle",
    )
    return len(hits)


def render_manifest(
    workspace: Path,
    *,
    command: str | None,
    tool: str | None,
    hits: int,
    auto_skills: list[str],
    auto_agent_skills: list[str] | None = None,
) -> str:
    auto_agent_skills = auto_agent_skills or []
    lines = [
        "# Session Manifest",
        "",
        f"**Generated:** {_now()}",
        f"**Workspace:** `{workspace}`",
        "",
        "Always-on memory bootstrap. **Every agent must read these files in order** before acting.",
        "Regenerated by `loop session-start` (any tool: Cursor, Claude Code, Codex, OpenCode, Grok, direct LLM).",
        "",
        "## Lifecycle",
        "",
        "- **Start:** `loop session-start` (or `/session-start`) - you are here",
        "- **End:** `loop session-end` (or `/session-end`) before stopping",
        "",
    ]
    if command:
        lines.append(f"- **Active command:** `{command}`")
    if tool:
        lines.append(f"- **Tool hint:** `{tool}`")
    lines.append(f"- **Session recall hits:** {hits}")
    lines.append("")

    lines.extend(["## Read order", ""])
    lines.append(f"1. `{MANIFEST}` (this file)")
    idx = 2
    for path in session_bootstrap_paths(workspace):
        if path.name == "SESSION_MANIFEST.md":
            continue
        try:
            rel = path.relative_to(workspace).as_posix()
        except ValueError:
            rel = str(path)
        exists = "ok" if path.exists() else "missing"
        lines.append(f"{idx}. `{rel}` ({exists})")
        idx += 1

    if auto_skills:
        lines.extend(["", "## Auto frontend skills", ""])
        for name in auto_skills:
            lines.append(f"- `{name}` - see `plan/AUTO_SKILLS.md`")

    if auto_agent_skills:
        lines.extend(["", "## Auto agent-development skills", ""])
        for name in auto_agent_skills:
            lines.append(f"- `{name}` - see `plan/AUTO_AGENT_SKILLS.md`")

    bootstrap = workspace / "plan" / "PLAN_BOOTSTRAP.md"
    if bootstrap.exists():
        lines.extend(
            [
                "",
                "## Plan bootstrap",
                "",
                f"- Read `{bootstrap.relative_to(workspace).as_posix()}` - auto scale + ultraplan route from user idea.",
            ]
        )

    if command in ("/plan-loop", "/ultraplan-loop", "/loop-engine", "/spec-clarify", "/spec-checklist") or (
        workspace / "plan" / "main_plan.md"
    ).exists():
        try:
            from plan_phase import render_phase_block

            lines.extend(["", render_phase_block(workspace, heading="## Plan phase")])
        except Exception:
            pass

    active = read_active_feature(workspace)
    if active:
        lines.extend(
            [
                "",
                "## Active feature",
                "",
                f"- **ID:** `{active.get('id')}` - {active.get('title', '')}",
                f"- **Path:** `{active.get('path')}`",
                "- Read `spec.md`, `feature-plan.md`, `tasks.md` in that folder during `/product-develop`.",
            ]
        )

    try:
        from model_config import active_summary, load_config

        cfg = load_config()
        if cfg.get("active", {}).get("provider"):
            lines.extend(
                [
                    "",
                    "## Model provider",
                    "",
                    f"- **Active:** {active_summary()}",
                    "- **Config:** `~/.loop-engineer/data/model.yml`",
                    "- See `plan/MODEL_STATUS.md` when present.",
                ]
            )
        else:
            lines.extend(
                [
                    "",
                    "## Model provider",
                    "",
                    "- Not configured - run `loop manage-model setup` for API-hosted inference outside IDE agents.",
                ]
            )
    except Exception:
        pass

    lines.extend(
        [
            "",
            "## Rules",
            "",
            "- Reuse `plan/SESSION_RECALL.md` - do not re-ask settled decisions.",
            "- Update `HANDOFF.md`, `DOUBTS.md`, `memories/MEMORY.md` before `loop session-end`.",
            "- Memory curator stages writes; user approves via `loop pending approve --all` when ready.",
            "",
        ]
    )
    return "\n".join(lines)


def session_start(
    workspace: Path,
    *,
    command: str | None = None,
    tool: str | None = None,
    text: str = "",
    skip_recall: bool = False,
) -> dict:
    ensure_memory_layout(workspace)
    hits = 0
    if not skip_recall:
        hits = run_recall(workspace)

    picks = run_router(workspace, extra=text, write=True)
    auto_names = [name for name, _ in picks]

    agent_picks = run_agent_router(workspace, extra=text, write=True)
    auto_agent_names = [name for name, _ in agent_picks]

    plan_bootstrap = None
    if text.strip() and command and any(c in (command or "") for c in ("/plan-loop", "/loop-engine", "plan", "loop-engine")):
        try:
            from plan_idea import bootstrap_plan

            plan_bootstrap = bootstrap_plan(workspace, text.strip())
        except Exception as exc:
            plan_bootstrap = {"error": str(exc)}

    manifest_path = workspace / MANIFEST
    manifest_path.parent.mkdir(parents=True, exist_ok=True)
    manifest_path.write_text(
        render_manifest(
            workspace,
            command=command,
            tool=tool,
            hits=hits,
            auto_skills=auto_names,
            auto_agent_skills=auto_agent_names,
        ),
        encoding="utf-8",
    )

    meta = read_meta(workspace)
    meta.update(
        {
            "started_at": _now(),
            "ended_at": None,
            "command": command,
            "tool": tool,
            "recall_hits": hits,
            "auto_skills": auto_names,
            "auto_agent_skills": auto_agent_names,
            "manifest": MANIFEST,
        }
    )
    write_meta(workspace, meta)

    db = state_db(workspace)
    init_db(db)
    log_session(
        db,
        workspace=str(workspace),
        command=command or "session-start",
        title="Session started",
        body=f"manifest={MANIFEST}; recall_hits={hits}; auto_skills={auto_names}; auto_agent_skills={auto_agent_names}",
        tags="lifecycle start",
    )

    return {
        "hits": hits,
        "auto_skills": auto_names,
        "auto_agent_skills": auto_agent_names,
        "manifest": str(manifest_path),
    }


def render_closeout(workspace: Path, report: dict, actions: list[str], pending: int) -> str:
    lines = [
        "# Session Closeout",
        "",
        f"**Generated:** {_now()}",
        f"**Workspace:** `{workspace}`",
        "",
        "Always-on memory closeout from `loop session-end`. Read `plan/MEMORY_REVIEW.md` for details.",
        "",
        "## Memory usage",
        "",
        f"- Memory: {report['memory_usage']['chars']}/{report['memory_usage']['limit']} chars",
        f"- User: {report['user_usage']['chars']}/{report['user_usage']['limit']} chars",
        "",
        "## Actions",
        "",
    ]
    if actions:
        lines.extend(f"- {a}" for a in actions)
    else:
        lines.append("- Memory within limits; closeout proposals staged if any.")
    lines.extend(
        [
            "",
            f"## Pending writes: {pending}",
            "",
        ]
    )
    if pending:
        lines.append("Run `loop pending list` and `loop pending approve --all` when the user accepts staged memory.")
    else:
        lines.append("No pending memory writes.")
    lines.extend(["", "## Next agent", "", "Read `plan/SESSION_MANIFEST.md` after the next `loop session-start`.", ""])
    return "\n".join(lines)


def session_end(
    workspace: Path,
    *,
    command: str | None = None,
    summary: str = "",
    apply: bool = False,
) -> dict:
    ensure_memory_layout(workspace)
    report = propose_updates(workspace)
    review_path = workspace / "plan" / "MEMORY_REVIEW.md"
    review_path.parent.mkdir(parents=True, exist_ok=True)
    review_path.write_text(render_report(workspace, report), encoding="utf-8")

    stage_only = not apply
    actions = apply_report(workspace, report, stage_only=stage_only)

    converge_note = ""
    if command and "product-develop" in (command or ""):
        try:
            from feature_converge import converge

            report_path, _ = converge(workspace)
            if report_path:
                converge_note = str(report_path.relative_to(workspace))
        except Exception as exc:
            converge_note = f"feature converge skipped: {exc}"
    if converge_note:
        actions.append(f"feature converge: {converge_note}")

    pending = len(list_pending(workspace))

    closeout_path = workspace / CLOSEOUT
    closeout_path.write_text(render_closeout(workspace, report, actions, pending), encoding="utf-8")

    handoff_excerpt = ""
    handoff = workspace / "HANDOFF.md"
    if handoff.exists():
        handoff_excerpt = handoff.read_text(encoding="utf-8", errors="ignore")[:800]

    body = summary.strip() or handoff_excerpt or review_path.read_text(encoding="utf-8")[:1200]
    db = state_db(workspace)
    init_db(db)
    log_session(
        db,
        workspace=str(workspace),
        command=command or "session-end",
        title="Session ended",
        body=body[:2000],
        tags="lifecycle end memory-review",
    )

    meta = read_meta(workspace)
    meta["ended_at"] = _now()
    meta["last_closeout"] = CLOSEOUT
    meta["pending_writes"] = pending
    write_meta(workspace, meta)

    return {
        "review": str(review_path),
        "closeout": str(closeout_path),
        "pending": pending,
        "actions": actions,
    }


def main() -> int:
    parser = argparse.ArgumentParser(description="Always-on session lifecycle (start/end).")
    parser.add_argument("phase", choices=("start", "end"))
    parser.add_argument("--workspace", default=None)
    parser.add_argument("--command", default=None, help="Active loop command e.g. /product-develop")
    parser.add_argument("--tool", default=None, help="Tool hint e.g. cursor, claude, codex")
    parser.add_argument("--text", default="", help="Extra context for routers (user message).")
    parser.add_argument("--skip-recall", action="store_true")
    parser.add_argument("--apply", action="store_true", help="Apply memory directly on end (default: stage).")
    parser.add_argument("--summary", default="", help="Optional closeout summary for state.db")
    args = parser.parse_args()

    workspace = resolve_workspace(args.workspace)

    if args.phase == "start":
        result = session_start(
            workspace,
            command=args.command,
            tool=args.tool,
            text=args.text,
            skip_recall=args.skip_recall,
        )
        print(f"session-start ok")
        print(f"  manifest: {result['manifest']}")
        print(f"  recall hits: {result['hits']}")
        if result["auto_skills"]:
            print(f"  auto skills: {', '.join(result['auto_skills'])}")
        if result["auto_agent_skills"]:
            print(f"  auto agent skills: {', '.join(result['auto_agent_skills'])}")
        print("  read plan/SESSION_MANIFEST.md first")
        return 0

    result = session_end(workspace, command=args.command, summary=args.summary, apply=args.apply)
    print("session-end ok")
    print(f"  review: {result['review']}")
    print(f"  closeout: {result['closeout']}")
    print(f"  pending writes: {result['pending']}")
    for action in result["actions"]:
        print(f"  - {action}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
